name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Navigate to speed-backend
      run: cd speed-backend

    - run: npm ci
      # No need to specify working-directory here, as you've navigated to speed-backend

    - run: npm run build --if-present
      # No need to specify working-directory here, as you've navigated to speed-backend

    - run: npm test
      # No need to specify working-directory here, as you've navigated to speed-backend
